routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\SizeController;
use App\Http\Controllers\Admin\StateController;
use App\Http\Controllers\Admin\SubCategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VendorController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::post('/attempt', [AuthController::class, 'attempt'])->name('attempt');
Route::get('/forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot_password');
Route::get('/email-verify/{token}', [AuthController::class, 'emailVerify'])->name('email_verify');
Route::get('/reset-password/{token}', [AuthController::class, 'resetPassword'])->name('reset_password');

Route::middleware(['auth'])->group(function () {

  // logout
  Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

  // change password
  Route::get('/change-password', [AuthController::class, 'changePassword'])->name('change_password');
  Route::post('/change-password/update', [AuthController::class, 'updatePassword'])->name('update_password');

  // Dashboard
  Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
  Route::get('/dashboard/state-wise-user-chart', [DashboardController::class, 'state_wise_user_chart'])->name('dashboard.state_wise_user_chart');
  Route::get('/dashboard/registered-user-chart/{duration}', [DashboardController::class, 'registered_user_chart'])->name('dashboard.registered_user_chart');
  Route::get('/dashboard/order-chart/{duration}', [DashboardController::class, 'order_chart'])->name('dashboard.order_chart');

  // Colors
  Route::get('/colors', [ColorController::class, 'index'])->name('colors.index');
  Route::get('/colors/data', [ColorController::class, 'getData'])->name('colors.data');
  Route::post('/colors/create', [ColorController::class, 'create'])->name('colors.create');
  Route::get('/colors/edit/{color}', [ColorController::class, 'edit'])->name('colors.edit');
  Route::post('/colors/update/{color}', [ColorController::class, 'update'])->name('colors.update');
  Route::get('/colors/delete/{color}', [ColorController::class, 'delete'])->name('colors.delete');
  Route::get('/colors/change-status/{color}', [ColorController::class, 'changeStatus'])->name('colors.changeStatus');
  Route::get('/colors/export', [ColorController::class, 'export'])->name('colors.export');

  // Sizes
  Route::get('/sizes', [SizeController::class, 'index'])->name('sizes.index');
  Route::get('/sizes/data', [SizeController::class, 'getData'])->name('sizes.data');
  Route::post('/sizes/create', [SizeController::class, 'create'])->name('sizes.create');
  Route::get('/sizes/edit/{size}', [SizeController::class, 'edit'])->name('sizes.edit');
  Route::post('/sizes/update/{size}', [SizeController::class, 'update'])->name('sizes.update');
  Route::get('/sizes/delete/{size}', [SizeController::class, 'delete'])->name('sizes.delete');
  Route::get('/sizes/change-status/{size}', [SizeController::class, 'changeStatus'])->name('sizes.changeStatus');
  Route::get('/sizes/export', [SizeController::class, 'export'])->name('sizes.export');

  // Brands
  Route::get('/brands', [BrandController::class, 'index'])->name('brands.index');
  Route::get('/brands/data', [BrandController::class, 'getData'])->name('brands.data');
  Route::post('/brands/create', [BrandController::class, 'create'])->name('brands.create');
  Route::get('/brands/edit/{brand}', [BrandController::class, 'edit'])->name('brands.edit');
  Route::post('/brands/update/{brand}', [BrandController::class, 'update'])->name('brands.update');
  Route::get('/brands/delete/{brand}', [BrandController::class, 'delete'])->name('brands.delete');
  Route::get('/brands/change-status/{brand}', [BrandController::class, 'changeStatus'])->name('brands.changeStatus');
  Route::get('/brands/export', [BrandController::class, 'export'])->name('brands.export');

  // States
  Route::get('/states', [StateController::class, 'index'])->name('states.index');
  Route::get('/states/data', [StateController::class, 'getData'])->name('states.data');
  Route::post('/states/create', [StateController::class, 'create'])->name('states.create');
  Route::get('/states/edit/{state}', [StateController::class, 'edit'])->name('states.edit');
  Route::post('/states/update/{state}', [StateController::class, 'update'])->name('states.update');
  Route::get('/states/delete/{state}', [StateController::class, 'delete'])->name('states.delete');
  Route::get('/states/change-status/{state}', [StateController::class, 'changeStatus'])->name('states.changeStatus');
  Route::get('/states/export', [StateController::class, 'export'])->name('states.export');

  // Cities
  Route::get('/cities', [CityController::class, 'index'])->name('cities.index');
  Route::get('/cities/data', [CityController::class, 'getData'])->name('cities.data');
  Route::post('/cities/create', [CityController::class, 'create'])->name('cities.create');
  Route::get('/cities/edit/{city}', [CityController::class, 'edit'])->name('cities.edit');
  Route::post('/cities/update/{city}', [CityController::class, 'update'])->name('cities.update');
  Route::get('/cities/delete/{city}', [CityController::class, 'delete'])->name('cities.delete');
  Route::get('/cities/change-status/{city}', [CityController::class, 'changeStatus'])->name('cities.changeStatus');
  Route::get('/cities/export', [CityController::class, 'export'])->name('cities.export');

  // Categories
  Route::get('/categories', [CategoryController::class, 'index'])->name('categories.index');
  Route::get('/categories/data', [CategoryController::class, 'getData'])->name('categories.data');
  Route::post('/categories/create', [CategoryController::class, 'create'])->name('categories.create');
  Route::get('/categories/edit/{category}', [CategoryController::class, 'edit'])->name('categories.edit');
  Route::post('/categories/update/{category}', [CategoryController::class, 'update'])->name('categories.update');
  Route::get('/categories/delete/{category}', [CategoryController::class, 'delete'])->name('categories.delete');
  Route::get('/categories/change-status/{category}', [CategoryController::class, 'changeStatus'])->name('categories.changeStatus');
  Route::get('/categories/export', [CategoryController::class, 'export'])->name('categories.export');

  // Sub Categories
  Route::get('/sub-categories', [SubCategoryController::class, 'index'])->name('sub_categories.index');
  Route::get('/sub-categories/data', [SubCategoryController::class, 'getData'])->name('sub_categories.data');
  Route::post('/sub-categories/create', [SubCategoryController::class, 'create'])->name('sub_categories.create');
  Route::get('/sub-categories/edit/{sub_category}', [SubCategoryController::class, 'edit'])->name('sub_categories.edit');
  Route::post('/sub-categories/update/{sub_category}', [SubCategoryController::class, 'update'])->name('sub_categories.update');
  Route::get('/sub-categories/delete/{sub_category}', [SubCategoryController::class, 'delete'])->name('sub_categories.delete');
  Route::get('/sub-categories/change-status/{sub_category}', [SubCategoryController::class, 'changeStatus'])->name('sub_categories.changeStatus');
  Route::get('/sub-categories/export', [SubCategoryController::class, 'export'])->name('sub_categories.export');

  // Users
  Route::get('/users', [UserController::class, 'index'])->name('users.index');
  Route::get('/users/data', [UserController::class, 'getData'])->name('users.data');
  Route::post('/users/create', [UserController::class, 'create'])->name('users.create');
  Route::get('/users/edit/{user}', [UserController::class, 'edit'])->name('users.edit');
  Route::post('/users/update/{user}', [UserController::class, 'update'])->name('users.update');
  Route::get('/users/delete/{user}', [UserController::class, 'delete'])->name('users.delete');
  Route::get('/users/change-status/{user}', [UserController::class, 'changeStatus'])->name('users.changeStatus');
  Route::get('/users/get-user-address/{user}', [UserController::class, 'getUserAddress'])->name('users.getUserAddress');
  Route::get('/users/get-cities/{state}', [UserController::class, 'getCities'])->name('users.getCities');
  Route::post('/users/update-address/{user}', [UserController::class, 'udpateAddress'])->name('users.udpateAddress');
  Route::get('/users/export', [UserController::class, 'export'])->name('users.export');

  // Vendors
  Route::get('/vendors', [VendorController::class, 'index'])->name('vendors.index');
  Route::get('/vendors/data', [VendorController::class, 'getData'])->name('vendors.data');
  Route::post('/vendors/create', [VendorController::class, 'create'])->name('vendors.create');
  Route::get('/vendors/edit/{vendor}', [VendorController::class, 'edit'])->name('vendors.edit');
  Route::post('/vendors/update/{vendor}', [VendorController::class, 'update'])->name('vendors.update');
  Route::get('/vendors/delete/{vendor}', [VendorController::class, 'delete'])->name('vendors.delete');

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\Admin\Orders\CompletedOrdersExport;
use App\Exports\Admin\Orders\PendingOrdersExport;
use App\Http\Controllers\Controller;
use App\Models\AddToCart;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Color;
use App\Models\Order;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Size;
use App\Models\SubCategory;
use App\Models\Vendor;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\DataTables\Facades\DataTables;

class OrderController extends Controller
{
    public function index() {
        return view('orders.pending');
    }

    public function completed() {
        return view('orders.completed');
    }

    public function getPendingData() {
        $orders = Order::select('orders.*', 'u.fname', 'u.lname', 'p.type', 'p.created_at as payment_date')
                    ->leftJoin('users as u', 'u.id', 'orders.user_id')
                    ->leftJoin('payments as p', 'p.id', 'orders.payment_id')
                    ->where('orders.status', Order::ACTIVE_ORDER)
                    ->whereNotNull('orders.payment_id')
                    ->withTrashed()
                    ->get();
        
        return DataTables::of($orders)
            ->addIndexColumn()
            ->addColumn('user_name', function($order){
                return ucwords($order->fname. " " .$order->lname);
            })
            ->editColumn('type', function($order){
                return $order->payment_date ? date('d-m-Y H:i A', strtotime($order->payment_date)) : "-";
            })
            ->editColumn('payment_date', function($order){
                return $order->payment_date ? date('d-m-Y H:i A', strtotime($order->payment_date)) : "-";
            })
            ->editColumn('note', function($order){
                return $order->note ?? "-";
            })
            ->addColumn('action', function($order){
                return '<button class="btn btn-success mr-2" title="Complete Order" onclick="viewOrder('.$order->id.', \'pending\')"><i class="fas fa-eye"></i></button>';
            })
            ->rawColumns(['user_name', 'payment_status', 'payment_date', 'action'])
            ->make(true);
    }

    public function getCompletedData() {
        $orders = Order::select('orders.*', 'u.fname', 'u.lname', 'p.type', 'p.created_at as payment_date')
                    ->leftJoin('users as u', 'u.id', 'orders.user_id')
                    ->leftJoin('payments as p', 'p.id', 'orders.payment_id')
                    ->where('orders.status', Order::INACTIVE_ORDER)
                    ->withTrashed()
                    ->get();
        
        return DataTables::of($orders)
            ->addIndexColumn()
            ->addColumn('user_name', function($order){
                return ucwords($order->fname. " " .$order->lname);
            })
            ->editColumn('payment_date', function($order){
                return date('d-m-Y H:i A', strtotime($order->payment_date));
            })
            ->editColumn('note', function($order){
                return $order->note ?? "-";
            })
            ->addColumn('action', function($order){
                return '<button class="btn btn-success mr-2" title="Complete Order" onclick="viewOrder('.$order->id.', \'completed\')"><i class="fas fa-eye"></i></button>';
            })
            ->rawColumns(['user_name', 'payment_date', 'payment_status', 'action'])
            ->make(true);
    }

    public function changeStatus($order) {
        $order = Order::where('id', $order)->withTrashed()->first();
        $order->status = $order->status == Order::ACTIVE_ORDER ? Order::INACTIVE_ORDER : Order::ACTIVE_ORDER;
        if($order->save()) {
            return response()->json([
                'status'    =>  1,
                'message'   =>  'Order status has been changed successfully!'
            ]);
        } else {
            return response()->json([
                'status'    =>  0,
                'message'   =>  "Something went wrong, please try again!"
            ]);
        }
    }

    public function show($order, $type) {
        $order = Order::select('orders.*', 'u.fname', 'u.lname', 'p.razorpay_payment_id', 'p.created_at as payment_date')
                    ->leftJoin('users as u', 'u.id', 'orders.user_id')
                    ->leftJoin('payments as p', 'p.id', 'orders.payment_id')
                    ->where('orders.id', $order)
                    ->withTrashed()
                    ->first();

        $cart_items = [];
        if($order) {
            $columns = [
                'add_to_cart.*',
                'p.name as product_name', 'p.status as product_status',
                'c.name as color', 'c.color as color_code', 'c.status as color_status',
                's.size as size', 's.status as size_status',
            ];
            $cart = AddToCart::select(...$columns)
                            ->leftJoin('products as p', 'p.id', 'add_to_cart.product_id')
                            ->leftJoin('colors as c', 'c.id', 'add_to_cart.color_id')
                            ->leftJoin('sizes as s', 's.id', 'add_to_cart.size_id')
                            ->where('order_id', $order->id)
                            ->get();
    
            if(!empty($cart)) {
                foreach ($cart as $key => $item) {

                    // product image
                    $images = ProductImage::where('product_id', $item->product_id)->get();
                    $all_images = [];
                    if(!empty($images)) {
                        foreach ($images as $key => $image) {
                            $all_images[] = is_file(public_path('images/products/'.$image->image)) && file_exists(public_path('images/products/'.$image->image))
                                            ? asset('images/products/'.$image->image)
                                            : asset('images/products/default.png');
                        }
                    }

                    $cart_items[] = [
                        'id'            =>  $item->id,
                        'order_id'      =>  $item->order_id,
                        'price'         =>  $item->price,
                        'quantity'      =>  $item->quantity,
                        'total_amount'  =>  $item->total_amount,
                        'created_at'    =>  date('d-m-Y', strtotime($item->created_at)),
                        'updated_at'    =>  date('d-m-Y', strtotime($item->updated_at)),
                        'product_details'   =>  [
                            'id'        =>  $item->product_id,
                            'name'      =>  $item->product_name,
                            'images'    =>  $all_images,
                            'status'    =>  $item->product_status
                        ],
                        'color_details'     =>  [
                            'name'      =>  $item->color,
                            'color'     =>  $item->color_code,
                            'status'    =>  $item->color_status
                        ],
                        'size_details'      =>  [
                            'size'      =>  $item->size,
                            'status'    =>  $item->size_status
                        ]
                    ];
                }
            }
        }
        $items = $cart_items;
        return view('orders.show', compact('order', 'items', 'type'));
    }

    public function pendingExport() {
        return Excel::download(new PendingOrdersExport, 'pending-orders-export.xlsx');
    }

    public function completedExport() {
        return Excel::download(new CompletedOrdersExport, 'completed-orders-export.xlsx');
    }
}

resources/views/orders/completed.blade.php
@extends('layouts.app')
@section('title', 'Amazing Ecom - Completed Orders')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Completed Orders</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Home</a></li>
            <li class="breadcrumb-item active">Completed Orders</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <div class="card-header">
              <div class="row align-items-center">
                <div class="col-lg-6">
                  <h3 class="card-title">Here is the list of completed orders.</h3>
                </div>
                <div class="col-lg-6 text-right">
                  <a href="{{route('orders.completed_export')}}" class="btn btn-info" title="Export Products"><i class="fas fa-download"></i> Export</a>
                </div>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="order-list" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Sr. No.</th>
                  <th>Customer Name</th>
                  <th>Amount</th>
                  <th>Payment Type</th>
                  <th>Payment Date</th>
                  <th>Customer Note</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody></tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<!-- View order Modal -->
<div class="modal fade" id="view-order-modal">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">View Order</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="view-order-content"></div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
@endsection

@push('footer-script')
<script>
  let table = $('#order-list').DataTable({
    autoWidth: true,
    responsive: true,
    processing: true,
    serverSide: true,
    ajax: '{{route("orders.completedData")}}',
    columns: [
      {data: 'DT_RowIndex', name: 'DT_RowIndex'},
      {data: 'user_name', name: 'user_name'},
      {data: 'final_amount', name: 'final_amount'},
      {data: 'type', name: 'type'},
      {data: 'payment_date', name: 'payment_date'},
      {data: 'note', name: 'note'},
      {data: 'action', name: 'action', orderable: true, searchable: true }
    ]
  })

  async function viewOrder(order, type) {
    $('#view-order-modal').modal('show');

    try {
      let response = await fetch(`{{url('/orders/show')}}/${order}/${type}`);

      if(!response.ok) {
        return swal("Something went wrong, Please try again!", {
          icon: "error",
        })
      }

      response = await response.text();
      $('#view-order-content').html(response)

      $('#product-list').DataTable()

    } catch (err) {
      console.error(err)
    }
  }
</script>
@endpush

resources/views/orders/pending.blade.php
@extends('layouts.app')
@section('title', 'Amazing Ecom - Pending Orders')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Pending Orders</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Home</a></li>
            <li class="breadcrumb-item active">Pending Orders</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <div class="card-header">
              <div class="row align-items-center">
                <div class="col-lg-6">
                  <h3 class="card-title">Here is the list of pending orders.</h3>
                </div>
                <div class="col-lg-6 text-right">
                  <a href="{{route('orders.pending_export')}}" class="btn btn-info" title="Export Products"><i class="fas fa-download"></i> Export</a>
                </div>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="order-list" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Sr. No.</th>
                  <th>Customer Name</th>
                  <th>Amount</th>
                  <th>Payment Type</th>
                  <th>Payment Date</th>
                  <th>Customer Note</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody></tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<!-- View order Modal -->
<div class="modal fade" id="view-order-modal">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">View Order</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="view-order-content"></div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
@endsection

@push('footer-script')
<script>
  let table = $('#order-list').DataTable({
    autoWidth: true,
    responsive: true,
    processing: true,
    serverSide: true,
    ajax: '{{route("orders.pedingData")}}',
    columns: [
      {data: 'DT_RowIndex', name: 'DT_RowIndex'},
      {data: 'user_name', name: 'user_name'},
      {data: 'final_amount', name: 'final_amount'},
      {data: 'type', name: 'type'},
      {data: 'payment_date', name: 'payment_date'},
      {data: 'note', name: 'note'},
      {data: 'action', name: 'action', orderable: true, searchable: true }
    ]
  })

  // update order status
  function changeStatus(order) {
    swal({
      title: "Are you sure?",
      text: "You want to change order status !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then(async (confirm) => {
      if (confirm) {
        try {
          let response = await fetch(`{{url('/orders/change-status')}}/${order}`);

          if(!response.ok) {
            return swal("Something went wrong, Please try again!", {
              icon: "error",
            })
          }

          response = await response.json();
          if(response.status) {
            swal(response.message, {
              icon: "success",
            })
            $('#view-order-modal').modal('hide');
            table.ajax.reload()
          } else {
            swal(response.message, {
              icon: "error",
            })
          }

        } catch (err) {
          console.error(err)
        }
      }
    })
  }

  async function viewOrder(order, type) {
    $('#view-order-modal').modal('show');

    try {
      let response = await fetch(`{{url('/orders/show')}}/${order}/${type}`);

      if(!response.ok) {
        return swal("Something went wrong, Please try again!", {
          icon: "error",
        })
      }

      response = await response.text();
      $('#view-order-content').html(response)

      $('#product-list').DataTable()

    } catch (err) {
      console.error(err)
    }
  }
</script>
@endpush

resources/views/orders/show.blade.php
<div class="row">
  <div class="col-md-12 mb-3">
    <h5 class="mb-3">Order Details</h5>
    <div class="row mb-3">
      <div class="col-lg-3">
          <strong>Customer Name</strong>
      </div>
      <div class="col-lg-9">
          {{ucwords($order->fname.' '.$order->lname)}}
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-lg-3">
          <strong>Razorpay Order ID</strong>
      </div>
      <div class="col-lg-9">
          {{$order->razorpay_order_id ?? "-"}}
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-lg-3">
          <strong>Amount</strong>
      </div>
      <div class="col-lg-9">
          {{$order->final_amount}}
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-lg-3">
          <strong>Razorpay Payment ID</strong>
      </div>
      <div class="col-lg-9">
          {{$order->razorpay_payment_id ?? "-"}}
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-lg-3">
          <strong>Payment Date</strong>
      </div>
      <div class="col-lg-9">
        {{$order->payment_date ? date('d-m-Y', strtotime($order->payment_date)) : "-"}}
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3">
          <strong>Customer Note</strong>
      </div>
      <div class="col-lg-9">
        {{$order->note ?? "-"}}
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <hr>
    <h5>Cart Items</h5>
    <div class="mb-3 text-right">
      @if($type == "pending")
        <button class="btn btn-success" onclick="changeStatus({{$order->id}})">Complete Order</button>
      @endif
    </div>
    <table id="product-list" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Sr. No.</th>
          <th>Product Image</th>
          <th>Product Name</th>
          <th>Price</th>
          <th>Quanity</th>
          <th>Colors</th>
          <th>Sizes</th>
          <th>Amount</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        @foreach($items as $key => $item)
        <tr>
          <td>{{$key+1}}</td>
          <td>
            @foreach ($item['product_details']['images'] as $key => $image)
              @if($key == 0)
                <img src="{{$image}}" width="50px">
              @endif
            @endforeach
          </td>
          <td>{{$item['product_details']['name']}}</td>
          <td>{{$item['price']}}</td>
          <td>{{$item['quantity']}}</td>
          <td>{{$item['color_details']['name']}}</td>
          <td>{{$item['size_details']['size']}}</td>
          <td>{{$item['total_amount']}}</td>
          <td>{{date('d-m-Y H:i A', strtotime($item['created_at']))}}</td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>